# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    schedule:
      interval: 'daily'
    assignees:
      - 'LordRonz'
      - 'znordrol'
    reviewers:
      - 'LordRonz'
      - 'znordrol'
    commit-message:
      prefix: 'chore(deps): '
    labels:
      - 'dependencies'
    ignore:
      - dependency-name: 'nanoid'
        update-types: ['version-update:semver-major']

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'LordRonz'
    reviewers:
      - 'LordRonz'
    commit-message:
      prefix: 'chore(deps): '
    labels:
      - 'dependencies'
