version: '3'

services:
  redis:
    image: 'redis:alpine'
    networks:
      - node-network

  node-app:
    build: .
    image: node-app
    environment:
      - PORT=3001
      - REDIS_HOST=redis
    ports:
      - '3001:3001'
    networks:
      - node-network

  python-app:
    build: py
    image: python-app
    ports:
      - '8000:8000'
    networks:
      - node-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    depends_on:
      - node-app
    networks:
      - node-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

networks:
  node-network:
    driver: bridge
