-- AlterTable
ALTER TABLE "ktp" ADD COLUMN     "ktpUrl" VARCHAR(255),
ALTER COLUMN "nama" DROP NOT NULL,
ALTER COLUMN "nik" DROP NOT NULL,
ALTER COLUMN "alamat" DROP NOT NULL,
ALTER COLUMN "rt_rw" DROP NOT NULL,
ALTER COLUMN "kel_desa" DROP NOT NULL,
ALTER COLUMN "kecamatan" DROP NOT NULL,
ALTER COLUMN "agama" DROP NOT NULL,
ALTER COLUMN "status_perkawinan" DROP NOT NULL,
ALTER COLUMN "pekerjaan" DROP NOT NULL,
ALTER COLUMN "kewarganegaraan" DROP NOT NULL,
ALTER COLUMN "ttl" DROP NOT NULL,
ALTER COLUMN "jenis_kelamin" DROP NOT NULL;
